// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://htsjwhuhfzcjruzwsdrf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh0c2p3aHVoZnpjanJ1endzZHJmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjUzMTMzMjMsImV4cCI6MjA4MDg4OTMyM30.hgaext_DvneamQDrl6LKrS7cxWDgyeTtq4fQbGflhxA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});